<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>nit</string>
  </array>
  <key>name</key>
  <string>Nit</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#strings</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#markup</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constant</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#storage</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variable</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#entity</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>character</key>
    <dict>
      <key>match</key>
      <string>('[^\\']'|'\\.')</string>
      <key>name</key>
      <string>string.character.nit</string>
    </dict>
    <key>comment-single-line</key>
    <dict>
      <key>match</key>
      <string>#.*</string>
      <key>name</key>
      <string>comment.singleline.nit</string>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment-single-line</string>
        </dict>
      </array>
    </dict>
    <key>constant</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>-?(([0-9]*.[0-9])|([0-9]+))+e-?[0-9]+</string>
          <key>name</key>
          <string>constant.numeric.float_exp.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>-?[0-9]*\.[0-9]+</string>
          <key>name</key>
          <string>constant.numeric.float.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>-?0(x|X)[0-9A-Fa-f_]+((u|i)(8|(16)|(32)))?</string>
          <key>name</key>
          <string>constant.numeric.hex.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>-?0(o|O)[0-7_]+((u|i)(8|(16)|(32)))?</string>
          <key>name</key>
          <string>constant.numeric.oct.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>-?0(b|B)[0-1_]+((u|i)(8|(16)|(32)))?</string>
          <key>name</key>
          <string>constant.numeric.bin.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>-?[0-9][0-9_]*((u|i)(8|(16)|(32)))?</string>
          <key>name</key>
          <string>constant.numeric.dec.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(true|false|null)\b</string>
          <key>name</key>
          <string>constant.language.nit</string>
        </dict>
      </array>
    </dict>
    <key>entity</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>[A-Z][a-zA-Z0-9_]*</string>
          <key>name</key>
          <string>entity.name.type.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>_[a-z][a-zA-Z0-9_]*</string>
          <key>name</key>
          <string>entity.other.attribute-name.nit</string>
        </dict>
      </array>
    </dict>
    <key>inlongstring-code</key>
    <dict>
      <key>begin</key>
      <string>{{{</string>
      <key>end</key>
      <string>}}}</string>
      <key>name</key>
      <string>incode.nit</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>inshortstring-code</key>
    <dict>
      <key>begin</key>
      <string>{</string>
      <key>end</key>
      <string>}</string>
      <key>name</key>
      <string>string.quoted.double.untitled</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>keyword</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(label|if|then|loop|else|while|for|do|end|in|with)\b</string>
          <key>name</key>
          <string>keyword.control.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(return|continue|break|abort)\b</string>
          <key>name</key>
          <string>keyword.breaks.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(nullable|once|new|var)\b</string>
          <key>name</key>
          <string>keyword.declaration.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(is)\b</string>
          <key>name</key>
          <string>keyword.annot.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(isa|as|type|isset)\b</string>
          <key>name</key>
          <string>keyword.types.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(assert|__debug__|super|implies)\b</string>
          <key>name</key>
          <string>keyword.misc.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(==|\+=|-=|!=|=|!|@|&lt;=&gt;|&lt;=|&lt;&lt;|&lt;|&gt;=|&gt;&gt;|&gt;|\(|\)|\[|\]|,|::|:|\.\.\.|\.\.|\.|\+|-|\*\*|\*|/|%|)</string>
          <key>name</key>
          <string>keyword.operator.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(and|not|or)\b</string>
          <key>name</key>
          <string>keyword.operator.boolean.nit</string>
        </dict>
      </array>
    </dict>
    <key>long-tquote-alt-string</key>
    <dict>
      <key>begin</key>
      <string>'''</string>
      <key>end</key>
      <string>'''</string>
      <key>name</key>
      <string>string.triple.alt.nit</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#inlongstring-code</string>
        </dict>
      </array>
    </dict>
    <key>long-tquote-string</key>
    <dict>
      <key>begin</key>
      <string>\"\"\"</string>
      <key>end</key>
      <string>\"\"\"</string>
      <key>name</key>
      <string>string.triple.nit</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#inlongstring-code</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\\]|\\.)</string>
          <key>name</key>
          <string>string.char.nit</string>
        </dict>
      </array>
    </dict>
    <key>markup</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>`{</string>
          <key>end</key>
          <string>`}</string>
          <key>name</key>
          <string>markup.raw.nit</string>
        </dict>
      </array>
    </dict>
    <key>simple-string</key>
    <dict>
      <key>begin</key>
      <string>\"</string>
      <key>end</key>
      <string>\"</string>
      <key>name</key>
      <string>string.quoted.double.untitled</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#inshortstring-code</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\\]|\\.)</string>
          <key>name</key>
          <string>string.char.nit</string>
        </dict>
      </array>
    </dict>
    <key>storage</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(fun|init|redef|class|interface|module|import|package|abstract|universal|enum)\b</string>
          <key>name</key>
          <string>storage.type.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(private|protected|public|intrude|extern)\b</string>
          <key>name</key>
          <string>storage.modifier.nit</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#long-tquote-alt-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#long-tquote-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#simple-string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#character</string>
        </dict>
      </array>
    </dict>
    <key>variable</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(self)\b</string>
          <key>name</key>
          <string>variable.language.nit</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[a-z][a-zA-Z0-9_]*</string>
          <key>name</key>
          <string>variable.other.nit</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.nit</string>
  <key>uuid</key>
  <string>6b33d803-1dfa-4063-b203-abc0409bd1bb</string>
</dict>
</plist>